openapi: 3.0.0
info:
  title: Lambda API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Greet a user.
      parameters:
        - in: query
          name: name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
